name: cashier_flutter
description: Kasiyer uygulamasının Flutter sürümü (Kuyumculuk Takip Programı)
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "logo/erenapplogo.png"
  adaptive_icon_foreground: "logo/erenapplogo.png"
  adaptive_icon_background: "#ffffff"
