name: cashier_flutter
description: Kuyumculuk kasiyer uygulaması
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1   # basit global state/token yönetimi için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
